import{S as L,a as m,i as u}from"./assets/vendor-89feecc5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const f=document.querySelector(".gallery"),c=document.querySelector(".searchform"),w=document.querySelector(".search-form"),h=document.querySelector(".spinner"),d=document.querySelector(".load_more");let g=40,a=1;const S=Math.ceil(100/g);let b=new L(".gallery a",{captionDelay:250,captionsData:"alt",close:!0,className:"modal-style"});b.on("show.simplelightbox",function(){});m.defaults.baseURL="https://pixabay.com/api";const q="41618210-7d4eb9e03ab25b6c1f3452a1d",i={key:q,q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:g,page:a};async function v(){p(),y();try{i.page=a;const o=await m.get("/",{params:i}),{hits:r}=o.data;if(r.length===0)return u.error({title:"Error",position:"topCenter",message:"Sorry, there are no images matching your search query. Please try again!"}),console.log(o.data);let n=r.reduce((s,e)=>s+`<li class="gallery-item">
                        <a class="gallery-link" href="${e.largeImageURL}">
                            <img class="gallery-image" data-source="${e.largeImageURL}" src="${e.webformatURL}" alt="${e.tags}" width="360" height="200"/>
                        </a>
                        <div class='title'>
                            <p>Likes:<span class="value">${e.likes}</span></p>
                            <p>Views:<span class="value">${e.views}</span></p>
                            <p>Comments:<span class="value">${e.comments}</span></p>
                            <p>Downloads:<span class="value">${e.downloads}</span></p>
                        </div>
                </li>`,"");f.insertAdjacentHTML("beforeend",n),b.refresh(),P(),a>=S?u.info({position:"topCenter",message:"We're sorry, there are no more posts to load"}):$()}catch(o){console.error(o)}}d.addEventListener("click",async()=>{y(),p(),a+=1,i.page=a;try{await v()}catch(s){console.log(s)}const n=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})});w.addEventListener("submit",o=>{if(o.preventDefault(),a=1,I(),y(),c.value.trim().length===0){u.error({title:"Error",position:"topCenter",message:"Sorry, Please choose a topic."});return}p(),i.q=c.value,v(),c.value=""});function I(){f.replaceChildren()}function P(){h.style.visibility="hidden"}function p(){h.style.visibility="visible"}function $(){d.style.visibility="visible"}function y(){d.style.visibility="hidden"}
//# sourceMappingURL=commonHelpers.js.map
