import{S as L,a as m,i as p}from"./assets/vendor-89feecc5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();window.scrollBy(0,window.innerHeight);window.scrollBy(0,-window.innerHeight);const h=document.querySelector(".gallery"),l=document.querySelector(".searchform"),q=document.querySelector(".search-form"),f=document.querySelector(".spinner"),c=document.querySelector(".load_more");let g=40;const S=Math.ceil(100/g);let a=1,b=new L(".gallery a",{captionDelay:250,captionsData:"alt",close:!0,className:"modal-style"});b.on("show.simplelightbox",function(){});m.defaults.baseURL="https://pixabay.com/api";const I="41618210-7d4eb9e03ab25b6c1f3452a1d",u={key:I,q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:g,page:a};async function w(){if(d(),v(),a>S){y(),p.error({position:"topCenter",message:"We're sorry, there are no more posts to load"});return}try{const o=await m.get("/",{params:u}),{hits:r}=o.data;if(r.length===0)return p.error({title:"Error",position:"topCenter",message:"Sorry, there are no images matching your search query. Please try again!"}),console.log(o.data);let n=r.reduce((s,e)=>s+`<li class="gallery-item">
                        <a class="gallery-link" href="${e.largeImageURL}">
                            <img class="gallery-image" data-source="${e.largeImageURL}" src="${e.webformatURL}" alt="${e.tags}" width="360" height="200"/>
                        </a>
                        <div class='title'>
                            <p>Likes:<span class="value">${e.likes}</span></p>
                            <p>Views:<span class="value">${e.views}</span></p>
                            <p>Comments:<span class="value">${e.comments}</span></p>
                            <p>Downloads:<span class="value">${e.downloads}</span></p>
                        </div>
                </li>`,"");h.insertAdjacentHTML("beforeend",n),b.refresh(),y(),$()}catch(o){console.error(o)}}c.addEventListener("click",async()=>{v(),d();try{a+=1,u.page=a;const s=await w()}catch(s){console.log(s)}const n=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})});q.addEventListener("submit",o=>{o.preventDefault(),a=1,l.value.trim().length!==0&&(P(),d(),u.q=l.value,w(),l.value="")});function P(){h.replaceChildren()}function y(){f.style.visibility="hidden"}function d(){f.style.visibility="visible"}function $(){c.style.visibility="visible"}function v(){c.style.visibility="hidden"}
//# sourceMappingURL=commonHelpers.js.map
